package app.librepipes.data.youtube

/**
 * A single downloadable stream (progressive, video-only or audio-only).
 * Maps directly onto a "format" entry of the InnerTube player response.
 */
data class StreamFormat(
    val url: String,
    val itag: Int,
    val mimeType: String,
    /** Container/extention-ish label: mp4, webm, m4a, opus, ... */
    val suffix: String,
    val bitrate: Int,
    val width: Int = 0,
    val height: Int = 0,
    val audioQuality: String? = null,
    val approxDurationMs: String? = null,
    /** Whether the format carries a video (avc1/vp9/av01/...) track. */
    val hasVideo: Boolean = true,
    /** Whether the format carries an audio (mp4a/opus/...) track. */
    val hasAudio: Boolean = false,
) {
    val resolution: String
        get() = if (width > 0 && height > 0) "${width}x$height" else ""
}

data class SubtitleTrack(
    val url: String,
    val languageTag: String?,
    val name: String?,
    val isAutoGenerated: Boolean,
)

enum class StreamType { NORMAL, LIVE, AUDIO }

/** A video chapter marker (start time within the video). */
data class Chapter(
    val title: String?,
    val startSeconds: Long,
)

/**
 * Everything needed to play or download a video, resolved from the
 * InnerTube player response (replaces NewPipe's StreamInfo).
 */
data class StreamInfo(
    val id: String,
    val title: String,
    val url: String,
    val thumbnailUrl: String? = null,
    val uploaderName: String? = null,
    val uploaderUrl: String? = null,
    val duration: Long = 0L,
    val viewCount: Long = 0L,
    val textualDate: String? = null,
    val streamType: StreamType = StreamType.NORMAL,
    /** Epoch millis when a premiere/live stream goes live; null otherwise. */
    val premiereAt: Long? = null,
    /** Progressive formats (audio+video combined). */
    val videoStreams: List<StreamFormat> = emptyList(),
    /** Adaptive video-only formats. */
    val videoOnlyStreams: List<StreamFormat> = emptyList(),
    /** Adaptive audio-only formats. */
    val audioStreams: List<StreamFormat> = emptyList(),
    val dashMpdUrl: String? = null,
    val hlsUrl: String? = null,
    val subtitles: List<SubtitleTrack> = emptyList(),
    /** Chapter markers, fetched from the watch page (player API no longer ships them). */
    val chapters: List<Chapter> = emptyList(),
) {
    val isLive: Boolean get() = streamType == StreamType.LIVE
}
